### ISSUE TITLE
[DOCS] Plugin not running in Github Actions workflow 

### ISSUE THREAD

**Issue by merobi-hub** [HaaLeo/pylint-file-header#5]
| Python Version | Pylint Version | pylintfileheader Version |
| -------------- | -------------- | ------------------------ |
|    3.9            |     pulled from Github actions           |         0.3.2                 |

# Description
The pylintfileheader plugin is evidently not running in a Github Actions workflow despite being installed successfully during the workflow and set as a plugin in `linter.yml`. 

## Expected Behavior
The plugin runs.

# Steps to Reproduce

1. Install the package with `pip` in a `run` command in `linter.yml`.
2. Define pylintfileheader as a plugin.
3. Use `file-header-path=pylint.header` to define the header.

# Settings
<details><pre><code>

analyse-fallback-blocks=no
#enable-all-extensions=
#errors-only=
#exit-zero=
extension-pkg-allow-list=
extension-pkg-whitelist=
fail-on=
fail-under=10
#from-stdin=
ignore=CVS
ignore-paths=
ignore-patterns=^\.#
ignored-modules=
#init-hook=
jobs=1
limit-inference-results=100
load-plugins=pylintfileheader
file-header-path=pylint.header
persistent=yes
py-version=3.9
recursive=no
suggestion-mode=yes
unsafe-load-any-extension=no
#verbose=
evaluation=max(0, 0 if fatal else 10.0 - ((float(5 * error + warning + refactor + convention) / statement) * 10))
msg-template=
#output-format=
reports=no
score=yes
confidence=HIGH,
           CONTROL_FLOW,
           INFERENCE,
           INFERENCE_FAILURE,
           UNDEFINED
disable=raw-checker-failed,
        bad-inline-option,
        locally-disabled,
        file-ignored,
        suppressed-message,
        useless-suppression,
        deprecated-pragma,
        use-symbolic-message-instead
enable=c-extension-no-member
logging-format-style=old
logging-modules=logging
max-spelling-suggestions=4
spelling-dict=
spelling-ignore-comment-directives=fmt: on,fmt: off,noqa:,noqa,nosec,isort:skip,mypy:
spelling-ignore-words=
spelling-private-dict-file=
spelling-store-unknown-words=no
notes=FIXME,
      XXX,
      TODO
notes-rgx=
contextmanager-decorators=contextlib.contextmanager
generated-members=
ignore-none=yes
ignore-on-opaque-inference=yes
ignored-checks-for-mixins=no-member,
                          not-async-context-manager,
                          not-context-manager,
                          attribute-defined-outside-init
ignored-classes=optparse.Values,thread._local,_thread._local,argparse.Namespace
missing-member-hint=yes
missing-member-hint-distance=1
missing-member-max-choices=1
mixin-class-rgx=.*[Mm]ixin
signature-mutators=
check-protected-access-in-special-methods=no
defining-attr-methods=__init__,
                      __new__,
                      setUp,
                      __post_init__
exclude-protected=_asdict,
                  _fields,
                  _replace,
                  _source,
                  _make
valid-classmethod-first-arg=cls
valid-metaclass-classmethod-first-arg=cls
additional-builtins=
allow-global-unused-variables=yes
allowed-redefined-builtins=
callbacks=cb_,
          _cb
dummy-variables-rgx=_+$|(_[a-zA-Z0-9_]*[a-zA-Z0-9]+?$)|dummy|^ignored_|^unused_
ignored-argument-names=_.*|^ignored_|^unused_
init-import=no
redefining-builtins-modules=six.moves,past.builtins,future.builtins,builtins,io
expected-line-ending-format=
ignore-long-lines=^\s*(# )?<?https?://\S+>?$
indent-after-paren=4
indent-string='    '
max-line-length=100
max-module-lines=1000
single-line-class-stmt=no
single-line-if-stmt=no
allow-any-import-level=
allow-wildcard-with-all=no
deprecated-modules=
ext-import-graph=
import-graph=
int-import-graph=
known-standard-library=
known-third-party=enchant
preferred-modules=
overgeneral-exceptions=BaseException,
                       Exception
max-nested-blocks=5
never-returning-functions=sys.exit,argparse.parse_error
ignore-comments=yes
ignore-docstrings=yes
ignore-imports=yes
ignore-signatures=yes
min-similarity-lines=4
exclude-too-few-public-methods=
ignored-parents=
max-args=5
max-attributes=7
max-bool-expr=5
max-branches=12
max-locals=15
max-parents=7
max-public-methods=20
max-returns=6
max-statements=50
min-public-methods=2
check-quote-consistency=no
check-str-concat-over-line-jumps=no
argument-naming-style=snake_case
#argument-rgx=
attr-naming-style=snake_case
#attr-rgx=
bad-names=foo,
          bar,
          baz,
          toto,
          tutu,
          tata
bad-names-rgxs=
class-attribute-naming-style=any
#class-attribute-rgx=
class-const-naming-style=UPPER_CASE
#class-const-rgx=
class-naming-style=PascalCase
#class-rgx=
const-naming-style=UPPER_CASE
#const-rgx=
docstring-min-length=-1
function-naming-style=snake_case
#function-rgx=
good-names=i,
           j,
           k,
           ex,
           Run,
           _
good-names-rgxs=
include-naming-hint=no
inlinevar-naming-style=any
#inlinevar-rgx=
method-naming-style=snake_case
#method-rgx=
module-naming-style=snake_case
#module-rgx=
name-group=
no-docstring-rgx=^_
property-classes=abc.abstractproperty
#typevar-rgx=
variable-naming-style=snake_case
#variable-rgx=

</code></pre></details>

**Comment by HaaLeo** [comment]
Hi @merobi-hub, thx for opening this issue. However, I do not completely understand what you try to do. Can you show me the GitHub action workflow which you try to run or even better point me to the repository where the error occurs?

**Comment by HaaLeo** [comment]
Closing the issue due to inactivity
